apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-pvc-e
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: smb-share-e
  storageClassName: ""
