apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-pvc-d
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: smb-share-d
  storageClassName: smb-storage-class
