apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/media/qbittorrent
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  targetNamespace: media
