apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: csi-driver-smb
      version: "latest"
      sourceRef:
        kind: HelmRepository
        name: kubernetes-csi
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
