apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-csi
  namespace: flux-system
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts