apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lens
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: lens
      version: "1.2.3"
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
  values:
    someKey: someValue
